# Generated by Django 5.2.5 on 2025-09-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_delay_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Cooldown period between notifications in seconds.', verbose_name='notification delay seconds'),
        ),
    ]
