# Generated by Django 5.2.5 on 2025-08-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lobby_created', 'Lobby created'), ('lobby_started', 'Lobby started'), ('lobby_ended', 'Lobby ended'), ('status_changed', 'Status changed'), ('participant_joined', 'Participant joined'), ('participant_left', 'Participant left')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.lobbyroom')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='game.lobbyparticipant')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='game.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
