# Generated by Django 5.2.5 on 2025-08-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='available_to_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='available to date'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='evaluation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.quiz'),
        ),
        migrations.AlterField(
            model_name='lobbyparticipant',
            name='session_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='lobbyparticipant',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
