# Generated by Django 5.0 on 2025-09-18 10:04

from django.db import migrations

# A list of the default tags you want to create.
DEFAULT_TAGS = [
    'Easy Difficulty',
    'Medium Difficulty',
    'Hard Difficulty',
    'General Knowledge',
    'Science',
    'History',
    'Geography',
    'Movies',
    'Music',
    'Sports',
    'Foods',
]

def create_initial_tags(apps, schema_editor):
    """
    Checks if any tags exist, and if not, creates the default ones.
    """
    Tag = apps.get_model('game', 'Tag')
    if Tag.objects.exists():
        # If there's already data, do nothing.
        return

    # Create the Tag objects from the list.
    tags_to_create = [Tag(name=tag_name) for tag_name in DEFAULT_TAGS]
    Tag.objects.bulk_create(tags_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_quizparticipation'),
    ]

    operations = [
        migrations.RunPython(create_initial_tags),
    ]